### ISSUE TITLE
Erro ao iniciar

### ISSUE THREAD

**Issue by diogorocha18** [zRitsu/MuseHeart-MusicBot#32]
Iniciei a primeira vez apenas com o token para testar e tem o seguinte erro: 

[root@cwp MusicBot]# bash start.sh
Iniciando bot (Verifique se o mesmo está online)...
Commit ver: 4fd1270fe3fa4b78b7d95e17bfd56d5e4f12efbc
------------------------------
Iniciando o servidor Lavalink (dependendo da hospedagem o lavalink pode demorar                                                       iniciar, o que pode ocorrer falhas em algumas tentativas de conexão até ele inic                                                      iar totalmente).
------------------------------
================================================
[OK] CocoMusic#6366 - error_handler.py Carregado.
================================================
[OK] CocoMusic#6366 - server_manager.py Carregado.
================================================
[OK] CocoMusic#6366 - skin_editor.py Carregado.
================================================
[OK] CocoMusic#6366 - music_settings.py Carregado.
================================================
[OK] CocoMusic#6366 - guild_fav_manager.py Carregado.
================================================
[OK] CocoMusic#6366 - help_cog.py Carregado.
================================================
[OK] CocoMusic#6366 - integration_manager.py Carregado.
================================================
[OK] CocoMusic#6366 - misc.py Carregado.
================================================
[ERRO] CocoMusic#6366 - Falha ao carregar/recarregar o módulo: player_resume
Traceback (most recent call last):
  File "/root/Discord-Bots/MusicBot/utils/client.py", line 917, in load_modules
    self.reload_extension(module_filename)
  File "/root/Discord-Bots/MusicBot/venv/lib/python3.10/site-packages/disnake/ex                                                      t/commands/common_bot_base.py", line 602, in reload_extension
    raise errors.ExtensionNotLoaded(name)
disnake.ext.commands.errors.ExtensionNotLoaded: Extension 'modules.player_resume                                                      ' has not been loaded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Discord-Bots/MusicBot/venv/lib/python3.10/site-packages/disnake/ex                                                      t/commands/common_bot_base.py", line 452, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/Discord-Bots/MusicBot/modules/player_resume.py", line 10, in <modu                                                      le>
    import aiosqlite
  File "/root/Discord-Bots/MusicBot/venv/lib/python3.10/site-packages/aiosqlite/                                                      __init__.py", line 6, in <module>
    from sqlite3 import (  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Discord-Bots/MusicBot/utils/client.py", line 389, in on_ready
    bot.load_modules()
  File "/root/Discord-Bots/MusicBot/utils/client.py", line 927, in load_modules
    raise e
  File "/root/Discord-Bots/MusicBot/utils/client.py", line 922, in load_modules
    self.load_extension(module_filename)
  File "/root/Discord-Bots/MusicBot/venv/lib/python3.10/site-packages/disnake/ex                                                      t/commands/common_bot_base.py", line 523, in load_extension
    self._load_from_module_spec(spec, name)
  File "/root/Discord-Bots/MusicBot/venv/lib/python3.10/site-packages/disnake/ex                                                      t/commands/common_bot_base.py", line 455, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
disnake.ext.commands.errors.ExtensionFailed: Extension 'modules.player_resume' r                                                      aised an error: ModuleNotFoundError: No module named '_sqlite3'
CocoMusic#3453 - [106349831649257069] Online.

podem me ajudar?

**Comment by zRitsu** [comment]
Qual hospedagem?

**Comment by zRitsu** [comment]
se for squarecloud, parece que recentemente houve uma mudança no sistema deles no qual comprometeu a instalação de alguns packages instalados (ja recebi vários report relacionado a isso)

pra tentar forçar uma reinstalação baixa o arquivo requirements.txt e envia pra lá via commit (site ou no server deles): https://github.com/zRitsu/disnake-LL-music-bot/blob/main/requirements.txt

caso não dê certo, faz backup da tua aplicação, deleta do zip essas pastas e arquivos (ignore as que não tiver no zip):
![image](https://github.com/zRitsu/disnake-LL-music-bot/assets/74823568/991086e3-fda6-47d1-b178-3981e2f93a1f)

e tenta reenviar
