### ISSUE TITLE
can help me?

### ISSUE THREAD

**Issue by LIKEaBORZ** [zRitsu/MuseHeart-MusicBot#39]
Nova conexão - Bot: [1132105898014277744] 127.0.0.1
[RPC client] - Os dados de rpc foram sincronizados com sucesso.
Command synchronization task has finished
LIKEaBORZ (RESERV)#6500 - Iniciando servidor de música: LOCAL
==================================================
Atenção: O bot [LIKEaBORZ (RESERV)#6500] (ID: 1132105898014277744) foi configurado no portal do desenvolvedor como bot público
lembrando que se caso o bot seja divulgado pra ser adicionado publicamente o mesmo terá que estar sob as condições da licença GPL-2: https://github.com/zRitsu/MuseHeart-MusicBot/blob/main/LICENSE
Caso não queira seguir as condições da licença no seu bot, você pode deixar o bot privado desmarcando a opção public bot acessando o link: https://discord.com/developers/applications/1132105898014277744/bot
==================================================
LIKEaBORZ (RESERV)#6500 - [1132105898014277744] Online.
Traceback (most recent call last):
  File "/home/runner/MuseHeart-MusicBot/venv/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 728, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/runner/MuseHeart-MusicBot/venv/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 1083, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/runner/MuseHeart-MusicBot/venv/lib/python3.10/site-packages/disnake/utils.py", line 567, in maybe_coroutine
    return await value
  File "/home/runner/MuseHeart-MusicBot/modules/music.py", line 891, in play
    query = query.replace("\n", " ").strip()
AttributeError: 'ParamInfo' object has no attribute 'replace'

LIKEaBORZ (RESERV)#6500 - Servidor de música: [LOCAL] está pronto para uso!

**Comment by zRitsu** [comment]
Try using command below in repl.it shell and restart your application:
```sh
bash quick_update.sh
```
