### ISSUE TITLE
Bug that occurs when the bot starts playing music

### ISSUE THREAD

**Issue by SeasonPhan** [zRitsu/MuseHeart-MusicBot#41]
using version: [f096a69](https://github.com/zRitsu/MuseHeart-MusicBot/commit/f096a69f6ecda77e6c2bc214502adb1374242382) 
lastest commit at the time of reporting

**How to Replicate:**
I'm uncertain about the specific steps to reproduce this issue, as it may be related to my unstable network connection.

**Behavior:**
1. I send a request to play music.
2. The bot updates the player message.
3. An error message appears in the console.
4. Subsequently, the bot ceases playing music and stops updating the music player message (screenshot attached below).
![image](https://github.com/zRitsu/MuseHeart-MusicBot/assets/61407079/98c64d43-b0a9-44d4-a253-f36a121671f2)

```
Baixando lista de servidores lavalink (arquivo: auto_lavalink.ini)
Database em uso: TinyMongo | Nota: Os arquivos da database serão salvos localmente na pasta: local_database
Commit ver: f096a69f6ecda77e6c2bc214502adb1374242382
------------------------------
================================================
[OK] Muse#4484 - error_handler.py Carregado.
================================================
[OK] Muse#4484 - help_cog.py Carregado.
================================================
[OK] Muse#4484 - legacy_cmds.py Carregado.
================================================
[OK] Muse#4484 - misc.py Carregado.
================================================
[OK] Muse#4484 - music.py Carregado.
================================================
[OK] Muse#4484 - music_settings.py Carregado.
================================================
[OK] Muse#4484 - player_resume.py Carregado.
================================================
[OK] Muse#4484 - server_manager.py Carregado.
================================================
Muse#4484 - Os comandos já estão sincronizados.
Falha ao conectar no servidor JustAPie: ClientConnectorError(ConnectionKey(host='lavalink.justapie.net', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11001, 'getaddrinfo failed'))
==================================================
Atenção: O bot [Muse#4484] (ID: 123456789123456) foi configurado no portal do desenvolvedor como bot público
lembrando que se caso o bot seja divulgado pra ser adicionado publicamente o mesmo terá que estar sob as condições da licença GPL-2: https://github.com/zRitsu/MuseHeart-MusicBot/blob/main/LICENSE
Caso não queira seguir as condições da licença no seu bot, você pode deixar o bot privado desmarcando a opção public bot acessando o link: https://discord.com/developers/applications/1187332659035254877/bot
==================================================
Muse#4484 - [1187332659035254877] Online.
Muse#4484 - Servidor de música: [Caliwyr / v3] está pronto para uso!
Muse#4484 - Servidor de música: [albinhakanson / v3] está pronto para uso!
Muse#4484 - Servidor de música: [sillydev2 / v3] está pronto para uso!
Muse#4484 - Servidor de música: [Darren / v3] está pronto para uso!
Muse#4484 - Servidor de música: [lexnet-eu / v3] está pronto para uso!
Muse#4484 - Servidor de música: [OrdinaryEnder / v3] está pronto para uso!
Traceback (most recent call last):
  File "C:\Users\SeaSon\Desktop\musetest2\wavelink\websocket.py", line 181, in process_data
    await self._node.on_event(payload)
  File "C:\Users\SeaSon\Desktop\musetest2\wavelink\node.py", line 376, in on_event
    await event.player.hook(event)
  File "C:\Users\SeaSon\Desktop\musetest2\utils\music\models.py", line 699, in hook
    if error_403 and self.node.retry_403:
       ^^^^^^^^^
UnboundLocalError: cannot access local variable 'error_403' where it is not associated with a value
```

**Comment by SeasonPhan** [comment]
I was showing the wrong picture in the report above, 

So lets imagine as if Muse Heart Music's message were Muse's

**Comment by SeasonPhan** [comment]
this might caused by public lavalink servers that i was using

i enable ONLY Local lavalink server and the bot runs fine
